name: Continus Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: running testing APP
        run: |
          npm ci
          npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run:  npm ci

      - name: build project
        run: npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (fetch repo metadata only)
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages || echo "gh-pages branch does not exist yet"
          git switch --orphan gh-pages
          git reset --hard

      - name: Copy files to root
        run: |
          cp -r ./dist/* .

      - name: Commit and Push to gh-pages
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Julio-Freitas/finance-tech.git gh-pages
